<?php
defined( 'ABSPATH' ) or exit;
function mbo_set_defaults()
{
    return array
    (
        'what_if_many_bumps' => 'random',
        'show_regular_price' => false,
        'show_free_tag'      => false,
        'submenu_location' => 'woocommerce',
'hooks' => array
(
    'woocommerce_review_order_before_submit',
),
        'type' => 'custom',
        'price_criteria' => 'custom',
        'price'          => '',
        'quantity'       => 1,
        'is_upsell'      => 0,
        'autoadd'        => 0,
        'hide'           => 0,
        'lead_text'     => __( "Yes! I want it", 'molongui-bump-offer' ),
        'lead_text_alt' => __( "I don't want this", 'molongui-bump-offer' ),
        'intro_text'    => __( "ONE TIME OFFER! Only $1", 'molongui-bump-offer' ),
        'body_text'     => __( "You can have access to this exclusive offer by ticking the box above. Click and add it to your order now for just $1. This offer is not available at any other time or place.", 'molongui-bump-offer' ),
        'cart_position'     => '',
        'checkout_position' => 'woocommerce_review_order_before_submit',
        'minicart_position' => '',
        'display_conditions_relation' => 'all',
        'min_order_value'             => '',
        'min_item_count'              => '',
        'box_border_style'      => 'dashed',
        'box_border_width'      => '3',
        'box_border_color'      => '#ff1900',
        'box_border_radius'     => 0,
        'box_border_animation'  => 'none',
        'box_bg_color'          => '#fbf8eb',
        'box_bg_transparent'    => 0,
        'box_shadow_size'       => 0,
        'box_shadow_color'      => '#ffffff',
        'box_align'             => 'center',
        'box_width'             => 100,
        'box_vertical_margin'   => 20,
        'box_horizontal_margin' => 0,
        'box_inner_padding'     => 14,
        'lead_bg_color'        => '#f6d857',
        'lead_bg_transparent'  => 0,
        'lead_arrow_icon'      => 'arrow-1',
        'lead_arrow_blink'     => 1,
        'cb_shadow'            => 1,
        'lead_font_size'       => 17,
        'lead_font_weight'     => 'bold',
        'lead_text_decoration' => 'none',
        'lead_text_transform'  => 'none',
        'lead_text_color'      => 'black',
        'intro_font_size'       => 15,
        'intro_font_weight'     => 'normal',
        'intro_text_decoration' => 'none',
        'intro_text_transform'  => 'none',
        'intro_text_align'      => 'left',
        'intro_text_color'      => '#ef4836',
        'intro_padding_top'     => 0,
        'intro_padding_bottom'  => 0,
        'intro_padding_left'    => 0,
        'intro_padding_right'   => 0,
        'body_font_size'       => 11,
        'body_font_weight'     => 'normal',
        'body_text_decoration' => 'none',
        'body_text_transform'  => 'none',
        'body_text_align'      => 'left',
        'body_text_color'      => 'black',
        'body_padding_top'     => 0,
        'body_padding_bottom'  => 0,
        'body_padding_left'    => 0,
        'body_padding_right'   => 0,
        'image_position'   => 'below',
        'image_align'      => 'center',
        'image_size'       => 100,
        'image_color'      => 'none',
        'image_responsive' => true,
        'hide_qty_input'              => true,
        'hide_qty_input_class'        => '',
        'hide_qty_input_parent_class' => '',
        'hide_qty_input_prev_class'   => '',
        'hide_qty_input_next_class'   => '',
        'keep_config' => 1,
        'keep_data'   => 1,
    );
}
add_filter( 'mbo/default_options', 'mbo_set_defaults' );